### ISSUE TITLE
Resolution/Distance is broken

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#1028]
You get inconsistent results when you want to keep resolution or distance constant while changing the energy from scan to scan. To fix it we need some code changes, where we keep either distance or resolution constant throughout. Which should it be?

MXCuBE was written to work in (set, modify, ...) *resolution*. This means that if you change the energy the detector must move to maintain resolution. It also means that the detector position you get depends on the beam position, and generally on the exact formula for defining 'resolution'. If you ever start working with offset detectors this becomes a mess. We have probably not noticed it because very few work with changing energy under workflow control.

For use in the GPhL workflows I have added some code that works in constant distance. E.g. AbstractResolution.update_energy will currently change the resolution while keeping the detector distance constant, when the energy changes. This is easier to make consistent, but most of MXCuBE is built on the assumption that resolution stays fixed. E.g. I found out that when starting acquisition on P14, acquisition parameters energy and resolution are passed to a detector server, but the actual value is not set till acquisition starts. Meanwhile passed-in values for the detector distance are simply ignored - or rather, the detector is moved, but the value for the resolution is still passed to the server and set later. It also turns out that even in mock mode energy changes do not take effect till acquisition starts (more or less, it should be a timing issue), so that you cannot set the energy and use the new energy to calculate the resolution. 

The combination is inconsistent, and needs changing.

A) We could rewrite everything so that it used the detector distance, and resolution was just calculated on the fly as needed. This would be more sensible and robust in the long run. Unfortunately that would require rewriting current acquisition code, including e.g. the P14 detector se4rver, so that is not likely to be popular.

B) Alternatively, we can get rid of the use of detector distances, e.g. from AbstractResolution.update_energy, so that energy and resolution are kept constant during calculations (I put it in, I think, so I can get rid of it). And make it clear in the documentation that this is how it works. But since that will change the current behaviour, inconsistent as that behaviour may be, we still need to agree first. 

What do people say? A or B? Or just let me do it with minimum disruption (which would mean B)?

**Comment by rhfogh** [comment]
I have had a closer look.

Both AbstractResolution.get_value and AbstractResolution,update_energy will update the resolution to match the current energy on the assumption that the detector distance remains fixed. 

You can put detector distances into the AcquisitionParameters, but they are not respected. AbstractCollect.do_collect calls the move_detector function, but that function is a no-op (except in CollectMockup). At P14, at least, energy and resolution are passed to a DetectorServer that sets the values at the start of acquisition, while the detector distance at most moves the detector beforehand, only for that detector position to be ignored and  overridden.

On a more general level there are lots of functions in AbstractColelct that are implemented as no-ops, but are never actively implemented (or used). That is a trap - one might call those functions without realising that they have no effect.  We ought to clean out AbstractCollect so that the functions there are either implemented or removed.

Meanwhile, changing energies between scans (as for wavelength interleaving) causes the resolution to change from scan to scan in a manner that I have found no way to control.  The only solution I can see would be to make it consistent throughout the code that either detector distance or resolution is a derived parameter while the other is fixed under energy change.

**Comment by rhfogh** [comment]
After a web meeting, rhfogh, @marcus-oscarsson, @beteva agreed on the following:

The expected functioning of resolution setting requires that
  
-  Changing the resolution causes a change in the detector distance, and _vice versa_. 

-  Changing the energy must keep  the detector distance constant and change the resolution. This matches the current code in AbstractEnergy and AbstractResolution

-  When setting up an acquisition from a queue entry containing both energy and resolution, the energy must be set first in order to guarantee that the final result matches both the energy and resolution passed in.  The code at the ESRF (using MultiCollect) should currently work this way.

Setting the detector distance as part of a queue entry may or may not be necessary; rhfogh may remove this functionality in an upcoming PR, which can then be discussed.

There are a number of functions in AbstractCollect (and AbstractMultiCollect) that are implemented as no-op, to be (optionally) overridden in subclasses. It is agreed that this is poor style and should eventually be refactored, but any action should be postponed until the refactoring of the queue system and the abstract collect classes can be done together.

**Comment by marcus-oscarsson** [comment]
Thanks for the excellent summary !
