### ISSUE TITLE
Would it be possible to generate requirements.txt file?

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#1063]
> Would it be possible to generate requirements.txt files in parallel with / from the pyproject.toml and poetry.lock files? This would allow people to work with non-poetry installations and make it easier (for some, at least) to deal with problems like the one I came across here (<https://github.com/mxcube/mxcubecore/issues/1061>).

_Originally posted by @rhfogh in https://github.com/mxcube/mxcubecore/issues/1061#issuecomment-2441511514_

**Comment by fabcor-maxiv** [comment]
@rhfogh, for confirmation, what would you like to see in this `requirements.txt` file?

* Only the direct dependencies with loose version constraints as in [`pyproject.toml`](https://github.com/mxcube/mxcubecore/blob/e8e1ba17fccad92503827a8e20bf125f4459e413/pyproject.toml#L26-L51)?
* All dependencies, including indirect dependencies with pinned versions as in `poetry.lock`?

**Comment by rhfogh** [comment]
@marcus-oscarsson  Not sure I know enough to give a good answer. Basically that you can put those requirements.txt files to pip or conda, get a full installation that way, and get something that works. In my normal way of working I would generally be happy with loose constraints and only pin versions if there was a specific reason that things would break otherwise. But you guys, understanding the installation procedure better than I do, might have something to say, here.

**Comment by fabcor-maxiv** [comment]
I feel like the best solution would be for you to curate your own file.

If I understood correctly from one of your other messages, you also want to have the mxcube parts installed as editable, right?

If you go with conda, it could be as simple as something like this:

```yaml
dependencies:
  - python=3.8
  - python-ldap=3.4.3
  - pip
  - pip:
    - --editable path/to/mxcubecore
    - --editable path/to/mxcubeqt
```

The tricky part is that not everyone has the same paths on their local filesystem, so we can not share this file in the GitHub repository.

I tested this briefly and it seems to work. We can probably refine after some iterations.

**Comment by rhfogh** [comment]
@fabcor-maxiv Great! That solved the problem (with a little extra experimentation). The result in in mxcubeqt  PR #462.

I shall close the issue now. the mxcubeweb install already worked fine, and this takes care of mxcubeqt much simpler than by adding extra requirements files and fiddling around with that. 

Question withdrawn.
