### ISSUE TITLE
Validation error for HOActuatorModel

### ISSUE THREAD

**Issue by HilbertCorsair** [mxcube/mxcubecore#1092]
I am getting a validation error that I managed to trace to the TangoMotor class of the detector_distance HO. 
I attached a print screen with the console output (it's not much and not super clear)
Does anyone have any hints on how to deal with this? 

![pydantic_error](https://github.com/user-attachments/assets/1938a6d0-e5ba-452a-85e0-dc49ee37c57e)

**Comment by rhfogh** [comment]
Reading the message, it looks like the 'state' attribute is not a string, as it should be. Admittedly it is hard to see how it could be set to anything else - adapter_base.state() has the code:
        return self._ho.get_state().name
Could there be some overriding function that does something else? Or could the relevant HO return something unexpected for its state? Could you go into the function that gives the error (with a debugger or print statements) and figure out what the values actually are?

BTW, if anyone ever thinks about refactoring adapter_base, could they please consider replacing functions like state(), read_only() etc. with Python properties? I, at least, automatically assume that obj.state is an attribute (and obj.get_state() is a function), so having a functions called state() is a bit confusing.

**Comment by beteva** [comment]
Could you, please, send your beamline configuration file.

**Comment by HilbertCorsair** [comment]
Thank you @rhfogh and @beteva! I checked but the error doesn't go through the state() function in the adapter_base. It is the self.data() in the dict() method in adapter_base that generates the error.  
I was able to trace it to [this line](https://github.com/mxcube/mxcubeweb/blob/9d40d8bfae3097bc26e24b544404385651d262f1/mxcubeweb/core/adapter/adapter_base.py#L337)  
it's the .dict() at the end that gives an error for the detector_distance HO. 

Here are some screenshots of the beamline config, detector and detector_distance configuration files (since github doesn't support .yml and .xml files)
![detector_distance](https://github.com/user-attachments/assets/2437d69d-a321-494b-92f2-3cd75aa92dc7)
![detector](https://github.com/user-attachments/assets/fc35764d-4bcf-4ca8-833e-868a21b133f9)
![beamline_config](https://github.com/user-attachments/assets/c25cb700-830e-4229-ac49-fb6370cfe36b)

**Comment by rhfogh** [comment]
Looks to me like this is merely the outer wrapper for the problem. Near as I can see the line you pinpoint calls AdapterBase.dict(); which is a one-liner calling self.data().dict(); which calls ActuatorAdapterBase.data(); which calls ActuatorAdapterBase._dict_repr(); which calls AdapterBase._dict_repr() to get its data. In the end it still comes down to the data being passed to the HOModel  (which come from the HO itself) somehow not matching the Pydantic definition, and from the error message it looks like the 'state' field is involved.

But I think you may have to get an mxcubeweb programmer on this. Both Antonia and I are closer to the core and hardware, and the entire adapter system is a complicated superstructure of functions calling other functions and wrapping other functions in ways defined to match the needs of the web interface. It is for instance not entirely clear to me why a function that is supposed to return a dictionary of values has to first get a dictionary of the values, then use these to create an intermediate object,  then extract from that object a dictionary with the same values you had in the first place.  There is undoubtedly a reason, having to do with how the adapter layer is supposed to fit into the web interface  in the first place, but I am not the best person to investigate it.

**Comment by HilbertCorsair** [comment]
Another strange thing is that the model for the HOActuatorModel is quite simple 
```
class HOActuatorModel(HOModel):
    value: float = Field(0, description="Value of actuator (position)")
    limits: Tuple[float, float] = Field((-1, -1), description="Limits (min max)")
```
It doesn't have a "state" and nothing is of type 'string'

**Comment by rhfogh** [comment]
@HilbertCorsair 
The model for HOActuatorModel is a subclass of HOModel - which does have a number of attributes, including 'state'. 

The values are actually set in AdapterBase._dict_repr(); in the case of 'state' through a call to self.state()

**Comment by beteva** [comment]
Hi @HilbertCorsair , it seems to me that you are probably not using the DetectorMockup, but some specific Detector HO, which you still call DetectorMockup. If this is the case, could you, please, send the code for this HO, as it looks like you have extra properties . There is also a typo when you define you detector distance HO - you need to have hwrid="/detector_distance" - you are missing the "/" in yous file

**Comment by marcus-oscarsson** [comment]
@rhfogh Your maybe not an `mxcubeweb` developer but you seem to have a really good understanding for how things work :). @beteva knows well how things work both in the web and core pars ;). @HilbertCorsair I think as both @beteva and @rhfogh points out that this is an issue with the under-laying `HardwareObject`. What you could do is to simply print the `attr_name` and `d` after line 70 in `beamline_adapter.py`. Like this you would see which hardware object this is and what values you are dealing with.

**Comment by HilbertCorsair** [comment]
Hi @beteva , hi @marcus-oscarsson  this is the code for the MockupDetector used at this point 
```python
import time

from mxcubecore.BaseHardwareObjects import HardwareObjectState
from mxcubecore.HardwareObjects.abstract.AbstractDetector import AbstractDetector


class DetectorMockup(AbstractDetector):
    """
    Descript. : Detector class. Contains all information about detector
                the states are 'OK', and 'BAD'
                the status is busy, exposing, ready, etc.
                the physical property is RH for pilatus, P for rayonix
    """

    def __init__(self, name):
        """
        Descript. :
        """
        AbstractDetector.__init__(self, name)

    def init(self):
        """
        Descript. :
        """
        AbstractDetector.init(self)

        self._temperature = 25
        self._humidity = 60
        self._actual_frame_rate = 50
        self._roi_modes_list = eval(
            self.get_property("roi_mode_list", '["0", "C2", "C16"]')
        )
        self._roi_mode = 0
        self._exposure_time_limits = eval(
            self.get_property("exposure_time_limits", "[0.04, 60000]")
        )
        self.update_state(self.STATES.READY)
        self.distance_motor_hwobj = self.get_object_by_role("detector_distance")

        """Get approx detector centre (default to Pilatus values)"""
        xval = self.get_property("width", 2463) / 2.0 + 0.4
        yval = self.get_property("height", 2527) / 2.0 + 0.4
        self._beam_centre = (xval, yval)

    def has_shutterless(self):
        """Returns always True"""
        return True

    def get_radius(self, distance=None):
        return 160

    def prepare_acquisition(self, *args, **kwargs):
        """
        Prepares detector for acquisition
        """
        return

    def start_acquisition(self):
        """
        Starts acquisition
        """
        return

    def restart(self) -> None:
        self.update_state(HardwareObjectState.BUSY)
        time.sleep(2)
        self.update_state(HardwareObjectState.READY)
```
The `attr_name` is `detector.detector_distance` , but calling `.dict()` on `self.app.mxcubecore.get_adapter(attr_name)` which itself is an object of class `mxcubeweb.core.adapter.motor_adapter.MotorAdapter`, results in an error.

**Comment by marcus-oscarsson** [comment]
What is the error from `MotorAdapter` ?

**Comment by beteva** [comment]
@HilbertCorsair Did you correct the typo in your config file and try if it works?

**Comment by rhfogh** [comment]
Seeing as this one is still running:

What I think you should do it to go into mxcubeweb/core/adapter/adapter_base.py, line 450, in ActuatorAdapterBase._dict_repr
and add the following lines:

print("HERE", self._ho)
print ("HERE", data)

Then run till you get an error and see what was printed out just before the error. Alternatively you can do something equivalent with a debugger, if you prefer. Either way you will see what was the value and it type for everything in the dictionary, and the class of the HardwareObject where the data came from. My prediction is that the type of data["state"] will not be a string, so that the problem will be in the get_state() function of that HardwareObject, but one way or the other you should know more.

**Comment by HilbertCorsair** [comment]
@beteva I changed the config file and addted the "/" to the hwrid  but it didn't change anything
@marcus-oscarsson  the error resulting from the MotorAdapter.dict() is the one posted at the top :
1 validation error for HOActuatorModel
state
str type expected (type=type_error.str) 
this hapens for self.ho.name() == "/detector_distance"
@rhfogh might be on to something :)
the print outputs before the error are : 
HERE <TangoMotor.TangoMotor object at 0x7a9599126950>
HERE {'name': 'detector.detector_distance', 'state': <HardwareObjectState.UNKNOWN: 0>, 'msg': '', 'type': 'MOTOR', 'available': True, 'readonly': False, 'commands': {}, 'attributes': {}, 'value': 405.009, 'limits': [115.0, 1001.0]}
This confirms the problem coming from the state of TangoMotor being a state object instead of a string

**Comment by rhfogh** [comment]
The plot thickens a bit.

The state value comes from AdapterBase._dict_repr (line 304 in my code)
                "state": self.state(),

Looking over all the 'def state' in my mxcubeweb they all return something.state.name or an explicit string. The only exception is the machine_info_adapter (which returns a value instead of a name - maybe a mistake?). If you double-check the local version of your adapters, is there a state() function anywhere that does not behave like this? 

You could try going to line 312 in adapter_base (in _dict_repr, at the end of the try: just before the except:) and adding:

print ("HERE", self)
print ("HERE2", self._ho)
print ("HERE3", self_ho.get_state())
print("HERE4", self.state())
print ("HERE5", self_ho.get_state().name)

and see what that gives you. We need to nail down where that <HardwareObjectState.UNKNOWN: 0> comes from

**Comment by HilbertCorsair** [comment]
Hre are the outputs 
```
HERE <mxcubeweb.core.adapter.motor_adapter.MotorAdapter object at 0x70f7b84f3580>
HERE2 <TangoMotor.TangoMotor object at 0x70f7e322df60>
HERE3 <HardwareObjectState.UNKNOWN: 0> 
HERE4 <HardwareObjectState.UNKNOWN: 0> 
HERE5 'UNKNOWN'
```
Looks like both self.state() and self._ho.state() return the same thing : a state object 
I don't think the .value in machine_info_adapter is a mistake. It returns a numeric value corresponding to the state (for state "UNKNOWN" it returns 0)
I think the self._ho.get_state() is suppose to rerun a state object but perhaps the .state() function could be modified.

**Comment by rhfogh** [comment]
This is really strange. In my code (updated to the latest develop version) the state() function in MotorAdapter looks like this:

    def state(self):
        return self._ho.get_state().name

which should definitely return a string.

Can you double check that the code you are calling has the same function?  And if it does put some print commands in MotorAdapter.state() to prove 1) that this function is indeed being called, and 2) what the values involved are at this point?

**Comment by HilbertCorsair** [comment]
Yes I thought so too but then I noticed that state is a method of MotorAdapter that inherits from BaseAdapter and redefines state to return `return self._ho.get_state()`return self._ho.get_state()`

**Comment by rhfogh** [comment]
Not in my code, it does not - and I just fetched down the mxcubeweb develop branch. Which branch are you on? And are you up to date?

Anyway, we seem to have found the problem - and fortunately it seems to have been already solved in the develop branch.

**Comment by HilbertCorsair** [comment]
You're right @rhfogh I checked the latest develop branch and there is indeed an extra `.name` in the return statement of the `state()` method of the MotorAdapter class. The branch I'm currently developing on is based on an slightly older version of develop
Thank you very much for the help! This was a very interesting exploration :)
