### ISSUE TITLE
Configuration files mxcube3 and mxcube2

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#335]
Unify the XML configuration files so that the same set of files can be used for both MXCuBE3 and MXCuBE2

**Comment by IvarsKarpics** [comment]
To be done in two weeks

**Comment by marcus-oscarsson** [comment]
This will become much easier when the abstract classes are in place and settled, we are in effect already doing this :)

**Comment by marcus-oscarsson** [comment]
A start could be to create a folder for configuration files that already are or can be made common
