### ISSUE TITLE
Duplicated MicrodiffKappaMotor and Qub

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubecore#340]
Hi,

There is MicrodiffKappaMot.py and MicrodiffKappaMotor.py. I guess it is a leftover after the merge. Can we remove the MicrodiffKappaMot.py
There are also hwobjs containing Qub:
* Camera.py
* LimaVideo.py
* MiniDiff.py
* ShapeHistory.py
* TangoLimaVideo.py
Can we remove them or create a new directory like archve?

**Comment by marcus-oscarsson** [comment]
I guess we can remove the HOs using Qub since what we are doing are breaking compatability with MXCuBE2 Qt3 in anyways. One simple have to use HardwareObjects 2.2 or 2.1 for MXCuBE2 Qt3.

@beteva has to answer for the MicrodiffKappaMotor, It does seem strange that there are two of them as you say.

**Comment by marcus-oscarsson** [comment]
Done
