### ISSUE TITLE
Centring

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubecore#397]
* Rename CentringMath to Centring
* Add centring methods

**Comment by marcus-oscarsson** [comment]
Centring should perhaps be part of AbstractSampleView, what do you think ?

**Comment by IvarsKarpics** [comment]
Yes, I agree.

**Comment by beteva** [comment]
Definitively! Sample view in my opinion should include **everything**, which combines the on-axis visualisation with the diffractometer motors/actuators.
