### ISSUE TITLE
Create AbstractMachineInfo

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#448]
Use MachineInfo as inspiration for AbstractMachineInfo

Add to the already existing methods:
- get_undulator_gaps()
- get_machine_current()
- get_machine_state_text()

Finally make sure that MachineInfo inherits AbstractMachineInfo

**Comment by laispc** [comment]
Maybe I can help on this one?

**Comment by marcus-oscarsson** [comment]
Sure, if you would like, Ill assign it to you :)

**Comment by marcus-oscarsson** [comment]
Solved by #553
