### ISSUE TITLE
AbstractProcessing or AbstractOfflineProcessing and AbstractOnlineProcessing

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#452]
Decide on the name and function of AbstractProcessing or  AbstractOfflineProcessing and AbstractOnlineProcessing

**Comment by IvarsKarpics** [comment]
I can take this issue.

**Comment by jordiandreu** [comment]
Conceptually, I like the idea of split in Offline and Online (at least in my idea of these two concepts).
Can we discuss about the meaning of these two? This should help to design the common and specific API for them. Maybe a base abstract class for both processing classes would be desirable?

**Online Processing:** Any processes on the raw data (images and/or metadata) triggered by mxcube whose results (processed images, parameters, etc...) are used as a feedback by the same mxcube i.e. EDNACharacterization.

**Offline Processing:** Any processes on the raw data (images and/or metadata) triggered by mxcube whose results are no longer required by mxcube i.e. EDNAProc.

**Comment by rhfogh** [comment]
@jordiandreu 
Sounds good.

**Comment by IvarsKarpics** [comment]
Maybe the inheritance could look like:
* AbstractProcedure
   - AbstractOfflineProcessing
      1 EDNAAutoprocessing
      2 OfflineProcessingMockup
   - AbstractOnlineProcessing
      1 OnlineProcessingMockup

To start implementing this one needs to define AbstractProcedure. I would suggest to accept this PR as it is now, work on AbstractProcedure and then come back to this.

**Comment by marcus-oscarsson** [comment]
@jordiandreu  sounds good, 
@IvarsKarpics also looks good if we move EDNACharacterisation to AbstractOnlineProcessing

I also agree that we can merge the related PR's and continue with AbstractProcedure

**Comment by rhfogh** [comment]
@IvarsKarpics 
Surely Characterisation is Online - you do it before the experiment and wait for it to be finished before you start. Or have I misubderstood something?
