### ISSUE TITLE
Should be lucidX a requirement?

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubecore#500]
There are to general modules that try to import the lucid library (either version 1 or 2):

- sample_centring
- QtGraphicsManager

Moreover, lucid 3 in not supported yet in the general code. Shall we support also lucid3? remove this dependency?

**Comment by IvarsKarpics** [comment]
In general it should be just lucid without release number. I would keep this dependency and maybe use a dynamic module import with imporlib.
In the future maybe we can come up with AbstractSampleCentering where all centering methods would be defined.
