### ISSUE TITLE
AbstractVideoDevice

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#549]
I started to look at the AbstractVideoDevice inorder to unify the objects using Tango to access the on axis camera. I know that both me and @IvarsKarpics said that we would take a look and there was maybe someone else interested as well ?. These objects are surely used by almost everybody so I would like to know what you think before I get started.

There are currently:
- TangoLimaVideoDevice  (Used by other applications at ESRF reusing MXCuBE) 
- TangoLimaVideo -> TangoLimaVideoLoopback (Used by MXCubE3)
- QtTangoLimaVideoDevice
- QtLimaVideo
- VimbaVideo (Used ?)
- VaporyVideo (Seems to be a simulation device is it used ?)

TangoLimaVideoDevice, QtTangoLimaVideoDevice and QtLimaVideo looks fairly similar, are all of these really used ?

TangoLimaVideo is currently not inheriting AbstractVideoDevice partly due to the Qt dependency. I would suggest to remove the Qt dependency on AbstractVideoDevice. I would further suggest either replace AbstractVideoDevice or add a (Abstract)LimaVideoDevice.

Like this we would have:
**AbstractVideoDevice and or (Abstract)LimaVideoDevice**

And inheriting those:
**QtTangoLimaVideoDevice and TangoLimaVideoLoopback and possibly VimbaVideo**

**Comment by IvarsKarpics** [comment]
At EMBL-HH we use VimbaVideo and QtAxisCamera. One can rename VimbaVideo.py to QtVimbaVideo.py because it depends on qt.
Sorry @marcus-oscarsson  for slow  or missing reaction from my side. Maybe during the next web meeting we could discuss the sample_view, cameras, centring and etc.

**Comment by marcus-oscarsson** [comment]
@IvarsKarpics its busy and different times so its completely understandable we are all more or less in the same situation :)

It would be great if we could get the SampleView discussed and merged before the meeting next week.

Id also like to attest start the work on the VideoDevice* objects and ideally have it done for the meeting

The discussions can of course continue on the meeting but I would like to have the basics merged. As for centring I think that CentringMath should be part of SampleView, we could also rename it to simply Centring.

**Comment by marcus-oscarsson** [comment]
So I missed the QtAxisCamera, we we can add that to the list :)

**Comment by marcus-oscarsson** [comment]
So Ill start to remove the Qt related things from AbstractVideoDevice and put in QtVideoDeviceBase, refactor AbstractVideoDevice slightly and then merge TangoLimaVideo and TangoLimaVideoDevice.

We can then discuss what to do with the others, how about that ?

**Comment by IvarsKarpics** [comment]
Sounds good!

**Comment by marcus-oscarsson** [comment]
After discussion it was decided that we would introduce a deprecated folder in which we store "deprecated" or unused hardware objects, so that they can be use for reference later.
