### ISSUE TITLE
Fix repository structure after refactoring

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubecore#612]
Hi @IvarsKarpics, @MartinSavko, @marcus-oscarsson, @rhfogh (@all)
IMHO it is worse to slightly change the structure of the repository, as the mxcubeqt repository did.
I would suggest two different folder levels as it is done with many python repositories: The mxcubecore package file should be in mxcubecore/mxcubecore folder and the repository files (setup.py, travis, etc...) should be in mxcubecore folder.

**Comment by marcus-oscarsson** [comment]
Done, as far as I understand it (Please let me know if something is still missing)
