### ISSUE TITLE
Abstract Classes cleaup proposal

### ISSUE THREAD

**Issue by beteva** [mxcube/mxcubecore#625]
There are few abstract classes, which do not correspond to the mxcubecore structure or are obsolete. This is an issue that suggests which abstract classes are to be refactored and which to be moved to the obsolete directory.
1. Refactoring:
  AbstractXRFSpectrum
  AbstractEnergyScan
  AbstractBeam
  AbstractDiffractometer
  AbstractVideoDevice

2. Remove to obsolete
   AbstractSlits
   AbstractAperture
   AbstractMCA

3. Left for later release
   AbstractProcedure
   AbstractOnlineProcessing
   AbstractMultiCollect
   AbstractCollect
   AbstractCharacterisation

To be discussed:
 - do we want to have abstract classes for all the roles, defined in the Beamline class
    machine_info - AbstractMachineInfo
    transmission - AbstractTransmission
    energy - AnstractEnergy
    flux - AbstractFlux
    beam - AnstractBeam
    safety_shutter, fast_shutter - AbstractShutter
    diffractometer - AbstractDiffractometer
    detector - AbstractDetector
    resolution - AbstractResolution
    sample_changer, plate_manipulator - AbstractSampleChanger
    sample_view - AbstractSampleView
    session
    lims
    hutch_interlock

 - shall we rename Session to AbstractSession

**Comment by rhfogh** [comment]
Do we want to have abstract classes for all the roles, defined in the Beamline class?
My general answer would be 'yes', if nothing else for documentation, so we know how they are supposed to be implemented and called. We can see about specific examples.

**Comment by IvarsKarpics** [comment]
- AbstractXRFSpectrum and AbstractEnergyScan should go to 3th category. At some point they should be inherited from AbstractProcedure, have well defined _pre_execute, _execute, _post_execute methods, data models and signals procedureStarted, procedureError, and etc.
- Do not see reasons why AbstractSlits and AbstractAperture should be removed.
- yes, we need abstract classes for roles defined in beamline. But not all. Session, lims, queue, xmlrpc can stay as they are. They are so called core of core :) If someone wants he/she can always re implement any class.

**Comment by marcus-oscarsson** [comment]
Done, part of a continuous process but the main work has been carried out
