### ISSUE TITLE
Add sample_temperature to beamline roles

### ISSUE THREAD

**Issue by beteva** [mxcube/mxcubecore#628]
Add sample_temperature to the roles of Beamline.py. We can access the temperature (of the cryo stream for time being) through HWR. This is also to prepare eventual control of the temperature (ramping, set ...)

**Comment by rhfogh** [comment]
Sounds reasonable.

**Comment by IvarsKarpics** [comment]
Is it a variable representing temperature at the sample position or it is a device? Would it make a sense to add a new role called cryo (AbstractCryo with variable temperature) or sample_environment?

**Comment by beteva** [comment]
It can be just a temperature, but it may as well represent a device. Having AbstractCryo in not contradictory to what I suggest, it is another aspect of it. The sample_temperature is just the way how you want to access it. Right now we access it via the diffractometer, but it is not quite right.  cryo is not a good name, because it may not be just cooling, but also heating.
I quite like sample_environment.

**Comment by beteva** [comment]
The idea behind the sample environment is to be able to access directly (and not through diffractometer) any sample environment device.
For now we only have reading of the temperature of the cryo stream. But in a near future, we will need changing this temperature (immediately or by ramping) and I could think of other parameters as pressure. For this I am not quite sure if the simple get_value/set_value mechanism is enough. If we do have only one parameter (e.g. only temperature) we could read it with get_value. Bit a simple set_value needs a prerequisite that it sets the value immediately. Than we may add other custom (not abstract) commands as ramp, start/stop ... Things get more complicated if we have more than one sample environment parameter, but this is not the case for now. For this I thought that AbstractSampleEnvironment is maybe not needed, as we cannot really specify generic methods, other than already available get/set value. if we do go for AbstractSampleEnvironment methods like get_units/set_units can be useful.

**Comment by rhfogh** [comment]
If there is a limited and predictable set of parameters (temperature, pressure, humidity???) I would vote in favour of having separate objects rather than a generic 'SampleEnvironment' - as you  say "we cannot really specify generic methods". If there may be many environment parameters with generalisable methods or you may need complex multi-parameters time courses, then maybe an 'AbstractSampleEnvironment'. But since this is far from my expertise I shall be happy with whatever you guys think best.

**Comment by beteva** [comment]
For time being there is only the temperature. I would not over complicate the Beamline object with a separate object per type. Maybe we could imagine, if need be later, of something like beamline.sample_environment.temperatute, but for now I would not do it, as we are not really sure how it is going to evolve. The only thing I am sure about is the fact that up to now we were only reading the temperature, while there will be a need to control it.

**Comment by marcus-oscarsson** [comment]
I don't think `AbstractSampleEnvrionment` is necessary at this stage, It would only add an extra layer of complexity to access temperature, humidity and possible pressure controllers. I would be tempted to add those controllers directly on the `Beamline` object directly. 

We ought to will quickly notice if there is a need to organise them under a common object such as `AbstractSampleEnvrionment`

**Comment by marcus-oscarsson** [comment]
We should decide on the names, i.e `cryo`, `humidifier` or other If we decide to add these directly on the beamline object

**Comment by jordiandreu** [comment]
In my opinion, I would not use such an abstract object to collect all these items since they do not need to be operated as a whole (like diffractometer motors, for instance) but rather define each instrument independenly, which will probably lead to a clear set of methods/variables/signals for each of these abstract classes (cryo, humidifier, etc..) extending the current mxcubecore API.

**Comment by beteva** [comment]
My idea was just ho have an entry in the beamline configuration, so afterwards any object like the cryo, humidifier ... can be accessed via common entry point.  Just like the diffractometer with it motors and the axillary equipment we can see the sample_environment with its different instruments, even if they are not connected to each other. Than, just like for the diffractometer we can define roles, but the API doers not change, if we add a new, unknown for now equipment. The decision than should be take if e.g cryo temperature will be accessed like HWR.sample_environment.cryo.get_value() or simply HWR.sample_environment.get_value(). Also I think that no matter the access, the signal should be simply value_changed.

**Comment by IvarsKarpics** [comment]
I agree with Antonia. It would be good to have few upper level placeholders, like diffractometer, machine_info and sample_environment.

**Comment by marcus-oscarsson** [comment]
I see, so there seems to be some different opinions here, either we add sample_environment to beamline and we add a AbstractSampleEnvironment that defines what it includes or we add each of those objects like cryo directly on beamline (leaving out (sample_environment)

Quick poll what do you think (perhaps also explaining how you reason):

 - A: Add a sample_environment object
 - B: Add cryo and humidifier directly on beamline

**Comment by beteva** [comment]
Resolved by PR #628
