### ISSUE TITLE
mxcubecore module, python path and import

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#630]
Dear All,

The current mechanism of loading HardwareObjects via `__import__` in [load_module](https://github.com/mxcube/mxcubecore/blob/3c4e7ae5ae12111abb377078e3a82ba6bd02216f/mxcubecore/HardwareObjectFileParser.py#L91) relies on the modules are in the python path.

It means that [this logic](https://github.com/mxcube/mxcubecore/blob/3c4e7ae5ae12111abb377078e3a82ba6bd02216f/mxcubecore/__init__.py#L30) is needed to append those modules to sys.path.

The consequence of this is that modules that are loaded via the xml and yaml files are imported relatively with the class name. 

Using mxcubecore as a python module with this logic as some unwanted side effects:
- sys.path is modified 
- Using an absolute import for instance `from mxcubecore.HardwareObjects import <hardware object>` wont result in the same module as the one loaded from the xml files (as the later is relative). Thus the isinstance check for instance fails.

I would suggest to change `load_module` so that it uses absolute imports instead.

Are there some other ideas or thoughts around this ?

**Comment by jordiandreu** [comment]
I'm not an expert on this topic, but I guess switching to absolute imports and do not relay on modifications on the **PYTHONPATH** via _sys.path_ is the safest way.

**Comment by marcus-oscarsson** [comment]
In my opinion a well, its a bit unexpected that a module inserts things into `sys.path`. However it has to be done for the current `load_module` to work properly and for client code to use i.e isinstance.

Ill see what I can do to rewrite load_module (without having to change the xml files) sometime the coming weeks. In the mean time let me know if you have any other ideas or objections ?

**Comment by jordiandreu** [comment]
Well, I think the way to do it,is using importlib module. Then you do not need to manually edit the sys.path.
https://stackoverflow.com/questions/301134/how-to-import-a-module-given-its-name-as-string

**Comment by marcus-oscarsson** [comment]
Sure, but the fact that a few modules like mockup (and maybe site specific modules) have been added to sys.path means that the xml files does not contain the full path to the object we want to load. So there needs to be some logic that sorts that out or the xml files needs to be updated accordingly (at least for the mockups)

**Comment by marcus-oscarsson** [comment]
That can definitely be done, I guess we just have to decide if we add some deductive logic that finds out in which module to look or if we change the xml files to include the entire full path. We can perhaps try with some deductive logic ?

**Comment by rhfogh** [comment]
This may need some thinking.

I completely agree wiht the principle that we should try to avoid  changing sys.path, for the reasons MO gives. 

Also, I think it is important to have a clean and simple import structure, and well worth reriting xml files to get there

For the specific case, samplechanges and mockups, I would favour just rewriting the xml files. It gets too opaque otherwise, it is a limited change, and it makes no sense to use this kind of teick for standard locations like samplechanger

FWIW I think importlib.import_module() is the right function, not \'__import\__'

BUT we need to check how it interacts with other places that changes sys.path, or, poreferably, get rid of taht mechanism everywhere.:

At the moment we have mechanisms to add directories to the PYTHONPATH for site-specific brick or HO directories, e.g. CUSTOM_BRICKS_PATH nad, CUSTOM_HARDWARE_OBJECTS_PATH (in mxcubeqt.\__init__, and the example below. In fact you find quite a lot if you do a global search for 'sys.path'

- mxcubeqt.\__init\__, line 126ff:
```
base_bricks_path = get_base_bricks_path()
sys.path.insert(0, base_bricks_path)
# add 'EMBL' 'ESRF' 'ALBA' ... subfolders to path
for root, dirs, files in os.walk(base_bricks_path):
    if root[root.rfind("/") :] != "/__pycache__" and root != base_bricks_path:
        sys.path.insert(0, root)

```

The start of mxcubecore.\__init\__

HatrdrwareObjects.add_hardware_objects_dirs

Ideally we would want a system where every class could be imported in only one way,  and we did not manipulate sys.path. That could be done if all configuration files had full paths, starting from inside I think we still need a lookup path for configuration files.
If we want some kind of plug-in system, we would need to think through how it should work and how to avoid taht we coudl import files with different paths, which is a recipe for trouble.

Quite an issue to look at.

**Comment by marcus-oscarsson** [comment]
I agree that its better if the XML and YAML files are as explicit as possible with as little "hidden" logic as possible.

A configurable lookup path (or list of paths) set either at startup (command line) or from a global configuration file
would be a better alternative if we sill think that we need to configure the lookup paths. This list of paths can then
of-course not be added to the `PYTHONPATH` but needs to be handled as you already pointed out through `importlib`.

These modules also needs to imported "absolutely" with respect to the `mxcubecore` package (I know a strange sentence
but I hope it makes sense :) ). They can otherwise not be imported correctly in the client modules `mxcubeweb` and 
`mxcubeqt`. This also puts some constraints  on any plug-in system.

Both the `CUSTOM_HARDWARE_OBJECTS_PATH` and the `CUSTOM_BRICKS_PATH` are "left overs" from Framework2
were one could look for both bricks and hardware objects outside of the Framework2 package itself. I don't know to which
extent its used today (we are not making any use of it here at ESRF).

What are your thoughts about the following:

- How many sites are currently using the `CUSTOM PATHS` (does anyone have a strong objection if its removed)

- Is there a need to specify additional lookup paths for `HardwareObjects` (not mentioning bricks as its for the Qt UI to handle), or is it enough to use `mxcubecore.HardwareObject` as a root

**Comment by rhfogh** [comment]
At the last developers' meeting, it was agreed that I should look for instances where the PYTHONPATH was modified and fix them. The 'fix them' part would be fairly big, so I would like to confirm that people want me to do it:

- As part of mxcubecore module loading (the starting point of this issue), HardwareObjects, HardwareObjects.sample_changer and HardwareObjects.mockup are put on the PYTHONPATH. Changing that would require changing pretty much all xml configuration files (which  am willing to do - if people want me to).

- HardwareObjects.ObjectController and HardwareObjects .XSData... modify sys.path. That is for whoever owns those files to look at if necessary.

- There are site-specific files for MAXIV and ALBA that modify sys.path; again that is for the owners to look at if necessary.

- test/pytest/conftest.py modifies sys.path. That looks OK and should presumably be left alone (?).

So, do people think I should start modifying all the xml files so as to get HardwareObjects, sample_changer and mockup off the PYTHONPATH?

**Comment by marcus-oscarsson** [comment]
I was thinking about the XML files: could we not just append "mxcubecore.HardwareObjects" to the object path in the code as we for the moment in anyways assume that all HardwareObjects are located in that root folder ?

I agree that it becomes more complicated for mockups which we in theory also could somehow resolve to but I think we should avoid being to implicit. 

In this way there is a minimal change to the XML files, its only the mockups that needs to be changed.

I agree that the other modifications to sys.path has to be removed and that its up to the owners of those files to see what needs to be done. Ill add it to the agenda for next developers meeting.

Marcus

**Comment by marcus-oscarsson** [comment]
Decided that will add "mxcubecore.HardwareObjects" in import logic

**Comment by marcus-oscarsson** [comment]
Solved
