### ISSUE TITLE
_collect in AbstractCollect

### ISSUE THREAD

**Issue by blavault** [mxcube/mxcubecore#635]
Hi,
As newcomers in the collaboration we are trying to use a datacollection module using AbstractCollect but this file is calling _prepare(cp), _get_sample_info(cp) and _collect(cp), which we cannot find anywhere in the beamline specific codes that are using AbstractCollect  like BIOMAX, ALBA, EMBL, SOLEIL. Does this code exists for those synchrotron but have not been pushed ? Could it be possible to update the master ?
Bernard

**Comment by IvarsKarpics** [comment]
Hi,

Current version of AbtractCollect in the master do not have _prepare, _get_sample_info and _collect. At some point there was a broken version of AbstractCollect and I reverted it to the previous working version (see https://github.com/mxcube/mxcubecore/commit/b2ab631e1a5e6c5ad684ad300a64bdc13a03988e)
Could you update your local master and check if it works?

Cheers,
Ivars

**Comment by blavault** [comment]
Dear Ivars,
We are working on sources updated at begining of 2021, just before the creation of mxcubecore (with HardwareRepository project and mxcube3). We thought we could continue to work on this one. I guess now that our master version is not runnable and that we have to merge mxcubecore with our HardwareRepositoty, right ?

Bernard

**Comment by marcus-oscarsson** [comment]
Was this issue solved ?
