### ISSUE TITLE
PyEPICS module missing in the requirements

### ISSUE THREAD

**Issue by laispc** [mxcube/mxcubecore#638]
EPICS classes require the Python module called `pyepics`, which is not in the requirements.

At the same time, it is a requirement only for those using EPICS. How about adding a note in the README about this need?

Thanks!

**Comment by beteva** [comment]
I would rather go for an extra requirements file. I believe we should do something like requirements_epics, requirements_tango, requirements_bliss... I would suggest to rise the question on the next developer's meeting.

**Comment by IvarsKarpics** [comment]
I am not sure if we have to list all site specific requirements. Would it be enough to provide a documentation in the hardware object and a note in the README.md? Lets discuss this during the next meeting.

**Comment by laispc** [comment]
@beteva , I like your idea of having separate requirements files for different control systems, so the installation gets lighter in disk space.
In addition to this, adding a note about these files in the README sounds good, similar to what @IvarsKarpics suggested.

**Comment by marcus-oscarsson** [comment]
We discussed this last meeting and it then seemed like the idea proposed by @beteva was well received by everyone. Meaning that we would have an extra requirement file for each specific control system i.e: requirements_epics, requirements_bliss. I will close this issue, please re-open of there are still something that needs to be dicussed.
