### ISSUE TITLE
Wavelength dependence for AbstractResolution functions

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#640]
You (well I) sometimes might want to calculate from resolution to distance for a wavelength that does not match the current wavelength. This could be achieved by adding an optional wavelength=None argument to the AbstractResolutiuon functions, similar to what we alrady have for AbstractDetector.get_beam_position:

    def resolution_to_distance(self, resolution=None, wavelength=None):
    def distance_to_resolution(self, distance=None, wavelength=None):
    def _calculate_resolution(self, radius, distance, wavelength=None):

In theory one could do something similar for get_value_at_corner, but I would advise against it, since a 'get_value' type function should probably not take extra parameters. 

The change would break no existing code, as behaviour would default to current behaviour, but since this is strictly speaking an API change,it needs to be raised as an issue before I put it into a PR.

Please comment (preferably positively).

**Comment by marcus-oscarsson** [comment]
Sounds like a good idea to me as well, I will raise the topic on the next developers meeting
