### ISSUE TITLE
Merge ExporterZoom HO and MicrodiffZoom HO

### ISSUE THREAD

**Issue by beteva** [mxcube/mxcubecore#641]
@all, the MicrodiffZoom now handles both motorized and numeric MD2 zoom. For this the class now inherits from ExporteNState and not from ExporterMotor any more. On the other hand there is ExporterZoom, which inherits from ExporterMotor and only handles the motorised zoom. I suggest to remove the ExporterZomm HO and only use MicrodiffZomm HO. The move_to_position, get_current_position_name are obsolete, replaced bu the standard set_value and get_value. The sort_predefined_positions_list is irrelevant, as we use the VALUES Enum and not a list any more. If the zoom_in and zoom_out methods are still needed, they can be added, to MicrodiffZoom.

**Comment by marcus-oscarsson** [comment]
What's the status of this, are we ready to remove `ExporterZoom` or does this still require some action ?

**Comment by beteva** [comment]
Issue resolved by PR #655
