### ISSUE TITLE
Repository versioning and releases

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#670]
How are we going to deal with the fact that we have two parallel applications, web, and qt, that depend on a single mxcubecore repository? We can make releases independently of the qt and web versions, but do we make releases of mxcubecore separately? It would be good to know that specific mxcube-qt and mxcube-web versions both depended on a specific version of mxcubecore, but how do we handle it?

**Comment by marcus-oscarsson** [comment]
I think it makes sense that we adopt the same versioning schema for the frontend applications as well and that we manage the dependency to mxcubecore as any other python library.

That would mean to pin a specific version of the frontend to a specific version of mxcubecore. I assume that frontend `develop` will refer to mxcubecore `develop`

**Comment by rhfogh** [comment]
Not quite sure I understand what you mean. Are you saying that mxcubeqt, mxcubeweb and mxcubecore should have their own separate semantic versioning and their own separate releases, and we track explicitly whiich front end version depends on which core version? I would certainly agree with that.

**Comment by marcus-oscarsson** [comment]
Yes that's what I suggest, we have already decided to do so within the MXCuBE3 community.  :)

**Comment by rhfogh** [comment]
Excellent! Should I close the issue, or do we need to leave it up for other people to comment if they want?

**Comment by marcus-oscarsson** [comment]
Hm, I think we can close it and the ones that feel that there is a need to discuss it can reopen it :)
