### ISSUE TITLE
Units for detector.get_beam_position

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#687]
We need to standardise on units for the detector.get_beam_position function. Without defined units you do not know what the return values mean, and you cannot use the function except by implicitly  assuming which beamline it is being run on. 

In AbstractDetector the function documentation says
"Beam position x,y coordinates [pixel]."

Yet the ESRF function returns values in mm.  It is tricky to see, since the actual values are determined by the configuration values of ax, ay, bx, and by, but it looks like lnls also uses mm, whereas SOLEIL uses pixels. 

Whatever it currently says in AbstractDetector, we can agree to use pixels or mm, or to have both get_beam_position_mm and get_beam_position_pixel, or probably other solutions, but could we agree on a single convention?

**Comment by rhfogh** [comment]
Opened temporarily as resource for discussion in MXCuBE developers' meeting

**Comment by marcus-oscarsson** [comment]
@rhfogh, All 

So I looked at this a bit further as we are implementing this at the moment. There might be a conversion missing in [get_beam_position()](https://github.com/mxcube/mxcubecore/blob/71978e39de50ef2f812012be8ffe10d1cc9a4214/mxcubecore/HardwareObjects/abstract/AbstractDetector.py#L227) depending on how want wants to configure beam center.

`
try:
            distance = distance or self._distance_motor_hwobj.get_value()
            wavelength = wavelength or HWR.beamline.energy.get_wavelength()
            metadata = self.get_metadata()

            beam_position = (
                float(distance * metadata["ax"] + metadata["bx"]),
                float(distance * metadata["ay"] + metadata["by"]),
            )
        except (AttributeError, KeyError):
            beam_position = (None, None)

        return 
`

As far as I can tell the beam position can't be anything else than **millimeters** using the calculation
above as long as the pixel to millimeters conversion is not included in ay and ax. 

Would it not make more sense to use **millimeters** for this interpolation and simply convert
the return value to pixels ?

**Comment by rhfogh** [comment]
Well, it all depends on what values you use for ax, ay, bx, and by. As far as I am aware it is not explicit anywhere what the unit of those values should be - they are in pixels at SOLEIL. In fact the lack of specification is arguably a weakness of the current system - the only 'specification' is in the fact that they must match the code that uses them. And that code is different in develop and in the MASSIF1 production code. In the develop branch the relevant code in abstract/AbstractDetector.get_radius is:

        beam_x, beam_y = self.get_beam_position(distance)
        pixel_x, pixel_y = self.get_pixel_size()
        rrx = min(self.get_width() - beam_x, beam_x) * pixel_x
        rry = min(self.get_height() - beam_y, beam_y) * pixel_y
        radius = min(rrx, rry)

which presupposes a position in pixels. It looks to me like the code in get_radius was changed to match an input in mm. 

We could consider making get_beam_position an abstract method (in pixels) and removing all references to ax,ay,bx,by from the abstract class. More coding, but less scope for confusion. But failing that we should probably try to enforce the correct nits for ax, ay, bx, by.

**Comment by marcus-oscarsson** [comment]
I **don't** there is any added value in abstracting away interpolation for the beam position in order for the unit of ax, by, bx and by could be on either pixels or mm.

Actually I think it would be a good thing if we could agree on the unit of those configuration/calibration parameters. The code as it is today somehow assumes that its in pixels. 

I have not really anything against this, I just found it a bit awkward to perform an interpolation with a distance in mm as input and calibration constants defined in pixels.
