### ISSUE TITLE
[Code Camp] - Testing

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#704]
Dear all,

Thanks to everybody that participated in today's code camp sessions.

There might still be a few that did not manage to get `pytest` to run with the latest code. If you need we are available to help you out to get it to work, let us know **here (in this issue)** if its the case **(and what we can help with).**

We will continue the practical part of writing tests tomorrow so its quite important that we all can run `pytest`.

We've had some very nice discussions around testing and CI. Among the things we discussed/did was to identify where testing effort is best spent. To start with we said that we would take another pass on the Abstract classes to identify which ones that are currently not tested or even unused and provide either a test for it or move it to deprecated if not used.

If you get started to write tests already today, please let us know which HardwareObject/part you are intending to test in this issue.

Let me know if there was something I forgot :)

**Comment by boyiliao** [comment]
Hi. Marcus

I forked the mxcubecore repository to my github yesterday.
After changing some code in /.github/workflow/build_and_test.yml, I see the python testing have been done by github actions.
Is that means the pytest is working? (I saw a pytest command in the last line in build_and_test.yml)

If I want to do more test on HardwareObject/part, I should try to modify the build_and_test.yml?
Thank you.

**Comment by marcus-oscarsson** [comment]
Good morning or afternoon :)

Yes, we reinstated the old CI by replacing Travis with GitHub actions a while back.

The easiest way to run the tests is simply to clone the project with the usual `git clone git@github.com:mxcube/mxcubecore.git` command. After that create a virtual environment and install all the dependencies, for instance using `conda`.

From there you should simply be able to run the test by issuing the command `pytest` in the project root. If you would like to run it with the pytest-cov (test coverage plugin) run `pytest --cov=.`

Something like this:

```
conda create --name mxcubecore-test
conda activate mxcubecore-test
conda install pip

# cd mxcubecore
pip install -e .
#pytest --cov=. 
```

**Comment by boyiliao** [comment]
Good morning :>
Thank you for the clear instructions.
It works well.
I am doing the pytest --cov=. right now, and I see the progress.

TOTAL       71946  67807        6%
===105 passed, 4 warnings===

**Comment by agruzinov** [comment]
All worked. Thanks!

Side note: for the the non-conda installation the command was pytest-3.
