### ISSUE TITLE
Queue system and web/Qt code divergence

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#718]
I should like to raise the issue of how to reorganise the MXCuBE queue and how to manage the relative needs of the MXCuBE-web and the MXCuBE-qt branches, as they arise in the context of PR #714 . The objectives and changes explicitly described in MO's header comment for the PR are quite wide-ranging, and I approve of all of them. But looking at (and discussing) the code there is a major and a minor problem that I think need addressing.

In summary I think this PR risks putting us back in a problem that has been quite common in the history of MXCuBE and ISPyB. There is one site with an active development group and a number of urgent needs - and, maybe, a certain lack of matching input from other sites. This site then proceeds to make a number of changes designed to fit their current circumstances, but that could have consequences for the structure of the project as a whole, and (maybe understandably) does not see it as their job to code for the specific needs of other sites. When the time comes for other sites to catch up, the main branch is slanted towards a site-specific way of working, and other sites will find it hard to avoid building their own specific branches or files, to fit their needs. And five years down the line someone gives a presentation about the problems of technical debt, supporting several parallel approaches in the same code base, and the difficulty of running a collaboration when the code is increasingly splitting in a number of separate bodies each attuned to the needs of a particular site. Eventually it is decided that a major refactoring is required to bring things back in sync. Do we maybe need to do something to avoid this?

Queue reorganisation
----------------------------------

The way the queue has worked until now, you first create a QueueModelObject. The QueueModelObjects form a parent-child tree that serves to give context, order etc. to the individual steps in the queue, in parallel to the queue_entries and views that for the queue proper. The triggering action is to call QueueModel.add_child(parent, child) with the QueueModelObjects. This then sends out the signal  "child_added", (parent, child), and that signal in turn triggers the addition of the new entry to the queue and the creation of QueueEntries and QueueItems (in the Qt interface) as needed. There are clearly some problems here that need looking at in the current code, e.g. a function like QueueModel.view_created clearly deals with Qt-specific objects and so should not live under mxcubecore. Still, the mxcube3 version (AFAICS) until now still worked by calling add_child (from inside components.queue), and catching the returned signal "child_added" to execute components.queue.queue_model_child_added - which made for a shared system between the two user interfaces.

However, in PR #714  e.g. a  SsxChipCollectionQueueEntry is generated with a Pydantic data object as input (not a QMO). The \_\_init\_\_ then generates a DataCollection QueueModelObject and attaches this to the QueueEntry. There is no call to add_child or signal 'child_added' that I can see, and AFAICS the DataCollection QMO is not attached to a parent. I have done a bit of looking to find where and how these new entries are added to the queue, but without success, so I could not figure out how the queue is now (henceforth?) supposed to work. The queue handling code that serves to put the SsxChipCollectionQueueEntry on the queue seems to be entirely in mxcubeweb, somewhere, with nothing in mxcubecore that would allow the Qt branches to latch on. 

Talking to Marcus I heard several good ideas on how we might want to reorganise the queue for the future: We might prefer to get rid of the QueueModelObjects and replace them with Pydantic data objects, which would have a number of beneficial consequences. We might want to get rid of the tree-of-QMO representation (which is partially duplicated at the queue entry level) and have object relationships solely there. We should communicate more via signals. These are all good ideas. But it is not clear to me that the details have been discussed, let alone agreed, by the developers. If there was at least a draft of the kind of queue structure we are aiming for in the future, we could check what problems we would need to consider, how we are moving towards it, what kind of changes we would have to make on the Qt side to get there, and what kind of constraints (if any) that would place on current changes. But I am not aware of any such draft. 

If this was up to me, I could only see a few alternatives:

1. I we want this PR as a minimal change that does not pre-empt how we want the queue to look in the future, I think it should be cut back so that it preserves the tree of QueueModelObjects, and adds to the queue via the established mechanism of calls to add_child and the child_added signal - maintaining a structure that can be shared between the web and Qt versions.
2. If we want to move towards a new queue structure already at this point, I think we need a page or two describing how the new structure is supposed to look, to serve as a guide for discussion and a framework for changes. We can hardly rework the queuing structure without having a plan for where we are going. 
3. If neither of these are possible, we could consider whether the PR rightfully belongs in the main code base shared between all sites at this point, or whether it should be seen as an independent ESRF-internal development, and discuss how we are going to handle divergences and merges between the two in the future.
4. Finally it may be that I have not properly understood the changes and/or am simply overreacting. If so we just need to bring in more sites than Grenoble and Cambridge so we can have a consensus to that effect. 

Hardware Object roles
---------------------

A less critical point that still involves basic strategy decisions is the question of global roles for hardware objects.  

PR #714 introduces a system of global roles that are set in configuration, and that serve as object ID, so that you can access any HardwareObject by its global role from the HardwareRepository level. This is a parallel system to the one we have introduced in the refactoring, where hardware objects are accessed using the Beamline as the central access point, and using the role names as pre-defined attributes (e.g. 'Beamline.detector.distance'). The need for this new system, as I understand from MO (he can probably explain it better), is that 
- "You need a way of listing e.g. all motors of the beamline"
- "It does not make sense to have every single hardware object directly under the beamline object"
- "Accessing hardware objects as attributes is not unique, as some hardware objects, e.g. the sample changer, are attributes of more than one other hardware object"
As I understand it, the global_role system is a re-implementation of the get_by_role function in the xml configuration system, where the object ID was the configuration file name - and, indeed, the global role name defaults to the file name. 

During the refactoring we explicitly wanted to get away from this system, because of the following problems:

- Having the hardware objects accessed as configured attributes of several different other hardware objects made it hard to track and maintain the system of hardware objects, and required changes in multiple configuration files for any change. We therefore opted to *not* have hardware objects defined as attributes in multiple places, and to access all hardware objects through a single access point: the Beamline object. 

- Having the hardware object identifiers defined in configuration meant that 1) the role names were site specific, so you could not write site-independent code that accessed them; 2) the role names were not defined in the code, and so linters could not check if an accessed hardware object existed, or what type it had. The solution was to set up the yaml configuration system so that configured properties (including e.g. Beamline.detector) had to be defined in the object \_\_init\_\_.  

Admittedly the situation is becoming more complex as we move towards using yaml configuration more widely and have to find a place to put the access for all individual motors. We might need to make some extensions to the Yaml configuration to support things properly this way, e.g. using multi-level access, such as 'Beamline.detector.distance', or by making functions to list all known HardwareObjects. But there is still a clear choice between using (a variant of) the yaml system, with the advantages it has, or going back to (a variant of) the get_by_role system, with its  higher flexibility. Using both systems in parallel would certainly give us the job of maintaining both while being able to rely on the advantages of neither. 

It seems that the question has been (re)raised: Which of the two systems for accessing hardware objects do we want to use?

**Comment by marcus-oscarsson** [comment]
> I should like to raise the issue of how to reorganise the MXCuBE queue and how to manage the relative needs of the MXCuBE-web and the MXCuBE-qt branches, as they arise in the context of PR #714 . The objectives and changes explicitly described in MO's header comment for the PR are quite wide-ranging, and I approve of all of them. But looking at (and discussing) the code there is a major and a minor problem that I think need addressing.
> 
> In summary I think this PR risks putting us back in a problem that has been quite common in the history of MXCuBE and ISPyB. There is one site with an active development group and a number of urgent needs - and, maybe, a certain lack of matching input from other sites. This site then proceeds to make a number of changes designed to fit their current circumstances, but that could have consequences for the structure of the project as a whole, and (maybe understandably) does not see it as their job to code for the specific needs of other sites. When the time comes for other sites to catch up, the main branch is slanted towards a site-specific way of working, and other sites will find it hard to avoid building their own specific branches or files, to fit their needs. And five years down the line someone gives a presentation about the problems of technical debt, supporting several parallel approaches in the same code base, and the difficulty of running a collaboration when the code is increasingly splitting in a number of separate bodies each attuned to the needs of a particular site. Eventually it is decided that a major refactoring is required to bring things back in sync. Do we maybe need to do something to avoid this?

As stated in the PR this work was meant to initiate the work on the improvements of the queue and that it would result in a series of PR's with discussions between each. The aim of such discussion would among other things be to avoid the situation that is expressed above. With that intention in mind I don't think we need to worry about the concern stated above, although I agree its good to keep it in mind.

> ## Queue reorganisation
> 
> The way the queue has worked until now, you first create a QueueModelObject. The QueueModelObjects form a parent-child tree that serves to give context, order etc. to the individual steps in the queue, in parallel to the queue_entries and views that for the queue proper. The triggering action is to call QueueModel.add_child(parent, child) with the QueueModelObjects. This then sends out the signal "child_added", (parent, child), and that signal in turn triggers the addition of the new entry to the queue and the creation of QueueEntries and QueueItems (in the Qt interface) as needed. There are clearly some problems here that need looking at in the current code, e.g. a function like QueueModel.view_created clearly deals with Qt-specific objects and so should not live under mxcubecore. Still, the mxcube3 version (AFAICS) until now still worked by calling add_child (from inside components.queue), and catching the returned signal "child_added" to execute components.queue.queue_model_child_added - which made for a shared system between the two user interfaces.

It would indeed be very nice to get rid of this Qt dependency from an mxcube-web perspective. Its not essential because there is a working solution today but it would be cleaner to replace the Qt related function calls with for instance signals. I don't consider this an important part of the current discussion though.

> 
> However, in PR #714 e.g. a SsxChipCollectionQueueEntry is generated with a Pydantic data object as input (not a QMO). The __init__ then generates a DataCollection QueueModelObject and attaches this to the QueueEntry. There is no call to add_child or signal 'child_added' that I can see, and AFAICS the DataCollection QMO is not attached to a parent. I have done a bit of looking to find where and how these new entries are added to the queue, but without success, so I could not figure out how the queue is now (henceforth?) supposed to work. The queue handling code that serves to put the SsxChipCollectionQueueEntry on the queue seems to be entirely in mxcubeweb, somewhere, with nothing in mxcubecore that would allow the Qt branches to latch on.

These new QueueEntries as explained in the PR could be made completely compatible with the current way of adding QueueModels. However the code for handling the generic display via JSONSchemas made possible with Pydatnic needs to be added in the Qt interface.

> 
> Talking to Marcus I heard several good ideas on how we might want to reorganise the queue for the future: We might prefer to get rid of the QueueModelObjects and replace them with Pydantic data objects, which would have a number of beneficial consequences. We might want to get rid of the tree-of-QMO representation (which is partially duplicated at the queue entry level) and have object relationships solely there. We should communicate more via signals. These are all good ideas. But it is not clear to me that the details have been discussed, let alone agreed, by the developers. If there was at least a draft of the kind of queue structure we are aiming for in the future, we could check what problems we would need to consider, how we are moving towards it, what kind of changes we would have to make on the Qt side to get there, and what kind of constraints (if any) that would place on current changes. But I am not aware of any such draft.

PR #714 does at the moment not address the entire project of restructuring the queue. It was meant as a minimal PR to get a few necessary features in place. The intention was then to continue this work if considered useful by the community. 

> 
> If this was up to me, I could only see a few alternatives:
> 
>     1. I we want this PR as a minimal change that does not pre-empt how we want the queue to look in the future, I think it should be cut back so that it preserves the tree of QueueModelObjects, and adds to the queue via the established mechanism of calls to add_child and the child_added signal - maintaining a structure that can be shared between the web and Qt versions.

This was the aim, and I think/hope we can achieve that, perhaps with some more updates.

> 
>     2. If we want to move towards a new queue structure already at this point, I think we need a page or two describing how the new structure is supposed to look, to serve as a guide for discussion and a framework for changes. We can hardly rework the queuing structure without having a plan for where we are going.

I think its a bit too early for this exercise but we can start some discussion and from there I could write a page or two.

> 
>     3. If neither of these are possible, we could consider whether the PR rightfully belongs in the main code base shared between all sites at this point, or whether it should be seen as an independent ESRF-internal development, and discuss how we are going to handle divergences and merges between the two in the future.

I really think we should do all that is possible to avoid any divergence. So for me this is not an option. 

> 
>     4. Finally it may be that I have not properly understood the changes and/or am simply overreacting. If so we just need to bring in more sites than Grenoble and Cambridge so we can have a consensus to that effect.

There is perhaps a few changes that would make this compatible from a mxcubecore perspective but the Qt interface work has to be done.

> 
> 
> ## Hardware Object roles
> 
> A less critical point that still involves basic strategy decisions is the question of global roles for hardware objects.
> 
> PR #714 introduces a system of global roles that are set in configuration, and that serve as object ID, so that you can access any HardwareObject by its global role from the HardwareRepository level. This is a parallel system to the one we have introduced in the refactoring, where hardware objects are accessed using the Beamline as the central access point, and using the role names as pre-defined attributes (e.g. 'Beamline.detector.distance'). The need for this new system, as I understand from MO (he can probably explain it better), is that
> 
>     * "You need a way of listing e.g. all motors of the beamline"
> 
>     * "It does not make sense to have every single hardware object directly under the beamline object"
> 
>     * "Accessing hardware objects as attributes is not unique, as some hardware objects, e.g. the sample changer, are attributes of more than one other hardware object"
>       As I understand it, the global_role system is a re-implementation of the get_by_role function in the xml configuration system, where the object ID was the configuration file name - and, indeed, the global role name defaults to the file name.
> 
> 
> During the refactoring we explicitly wanted to get away from this system, because of the following problems:
> 
>     * Having the hardware objects accessed as configured attributes of several different other hardware objects made it hard to track and maintain the system of hardware objects, and required changes in multiple configuration files for any change. We therefore opted to _not_ have hardware objects defined as attributes in multiple places, and to access all hardware objects through a single access point: the Beamline object.
> 
>     * Having the hardware object identifiers defined in configuration meant that 1) the role names were site specific, so you could not write site-independent code that accessed them; 2) the role names were not defined in the code, and so linters could not check if an accessed hardware object existed, or what type it had. The solution was to set up the yaml configuration system so that configured properties (including e.g. Beamline.detector) had to be defined in the object __init__.
> 
> 
> Admittedly the situation is becoming more complex as we move towards using yaml configuration more widely and have to find a place to put the access for all individual motors. We might need to make some extensions to the Yaml configuration to support things properly this way, e.g. using multi-level access, such as 'Beamline.detector.distance', or by making functions to list all known HardwareObjects. But there is still a clear choice between using (a variant of) the yaml system, with the advantages it has, or going back to (a variant of) the get_by_role system, with its higher flexibility. Using both systems in parallel would certainly give us the job of maintaining both while being able to rely on the advantages of neither.
> 
> It seems that the question has been (re)raised: Which of the two systems for accessing hardware objects do we want to use?

The `beamline` object is a very nice concept where a set of well known components are gathered that can be easily accessed through a common object. The roles are clearly well defined. However with this system we have to hardcode every component in the `beamline` object to know its role. There is no way of simply adding a `HardwareObject` by adding its configuration file and knowing its id/role. The `global role` concept is a way to give such an hardware object an ID. The word ID was simply avoided because it was somehow already taken within HardwareRepository. We need to be able to retrieve all `HardwareObjects` via an ID in mxcube-web and that was not possible without the `global_role` concept.

It can be done differently but we need to add all relevant `HardwareObjects` to the `beamline` object if we want to use it as a root/source for these id's. I'm fine with both but I would prefer If we did not have to add everything statically tot he `beamline` object.

**Comment by rhfogh** [comment]
You are quite right that there is a lot of work to be done to restructure the queue system, make use of the Pydantic data structures, change things to make use of JSON data structures on the Qt side (that is a big one) etc. - and that we are hardly in a position to make a specification yet. I am taking that in my stride, though - it will be work, but the end result should be worth it and  we were never getting the queue sorted out without a lot of work. The changes envisaged here seem to split up reasonably well, and one can see how one could move stepwise to get to the goal, even if the details are TBD.

My issue is on a very specific point: Currently we have a tree of QueueModelObjects (TaskNodes), in mxcubecore, that you use for navigation between different tasks (e.g. getting to the Sample from the DataCollection). The rest of the queue simply reflects that TaskNode tree. Also you add an object to the queue by calling add_child (parent, child); this then sends out the "child_added" signal, which is caught downstream and triggers all the things that need doing in whatever interface. It looks to me like the PR is bypassing this system, and introducing a new way of structuring the queue, navigating the structure, and adding items to it. To me that means that I no longer know what to do to add an object to the queue, or how to find and access the objects already there. Here, before we start bypassing the old system, I would like to know more about how the new way of structuring, navigating and populating the queue is going be.

It might be possible to do without the global_role without having to add every single hardware object directly at the beamline level; one might for instance add them in a defined location lower down, detector.distance, diffractometer.omega, etc. I just think we need to make a choice here. As you will have noticed I prefer the beamline system, but if we decide that we need (or prefer) the flexibility of being able to add new object with configured role names, I think it might be better to drop the beamline system altogether, and concentrate on finding a way of standardising the global role names of as many objects as possible. That way, at least, we would only have one system to maintain, and only one place to look when trying to access a HardwareObject.

**Comment by marcus-oscarsson** [comment]
I've made some changes that adds a `QueueModel` in the structure  `MODEL_QUEUE_ENTRY_MAPPINGS` for each dynamically created `QueueEntry`. Like this these new `queue entries` using pydantic can be seen and used as any other `QueueEntry`. The only inconvenience is in the implementation of the `QueueEntry` where we need to add a definition of a new `QueueModel`.

With this change we can still generate the queue entries from a tree of QueueModels and the `QueueModel` tree can be used as before. Maybe this is enough for the moment, at least as a first step, until we've decided how to change (if at all) the structure of the `QueueModel/Entry `tree ? 

I've started to look at the global_role and tried to come up with a solution using as we mentioned before "dotted paths" with the beamline object as a root i.e beamline.detector.distance. However, there are still some details to work out for this to function as we would like.

**Comment by rhfogh** [comment]
@marcus-oscarsson 
This looks very good. If we can use the QueueModel tree as before - until we make a considered decision to replace it with something else - I can see no problem with the rest (apart from the global_role, which you also discuss). My regrets for the extra work, and a lot of thanks for taking the queue reorganisation so far forward.
