### ISSUE TITLE
Use lucid3 from pypi

### ISSUE THREAD

**Issue by beenje** [mxcube/mxcubecore#738]
In `pyproject.toml`, `lucid3` dependency is installed from GitHub: https://github.com/mxcube/mxcubecore/blob/46187c4b4206f83fffe5e0bb3c98c767bcf0ace9/pyproject.toml#L46

We don't have access to internet on our beamlines and have to patch that file to install `mxcubecore`. `lucid3` is on pypi: https://pypi.org/project/lucid3/

Can't we specify this version? (latest is 3.0.0).

**Comment by marcus-oscarsson** [comment]
Sure why not, we can do that now when we have a nice package on PyPi. I'm not sure how you will be able to download packages from pypi if you don't have a internet connection. I guess regardless of where the source/package is located that you need to download it ?

**Comment by marcus-oscarsson** [comment]
Maybe you or one of your colleagues (@meguiraun, @meghdadyazdi ) can make a PR for this ?

**Comment by rhfogh** [comment]
I am in favour of this - I am working on making a docker that runs the MXCUBE Qt version with mxcubecore (PR and request for help soon), and I could not figure out how to install direct from github to the docker.

**Comment by beenje** [comment]
We have an internal Pypi repo that includes a "proxy" to the external pypi, so we can download pypi package without direct internet connection. I can make a PR.
