### ISSUE TITLE
Setup Sphinx-based documentation

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#797]
Similar to what was done for MXCUbe-Web: https://github.com/mxcube/mxcubeweb/issues/1053

We could probably move the content from the [wiki](https://github.com/mxcube/mxcubecore/wiki) into the Sphinx-based documentation, because then it is under control of git (with pull requests, reviews, etc.).

**Comment by fabcor-maxiv** [comment]
Not sure how that would play with the current content of the `doc` directory, I have no understanding of what is in that directory. Maybe @rhfogh can comment on this.

**Comment by rhfogh** [comment]
The MEPS subdirectory I have no idea about.

The json_schema_gui directory is hand-made developers' documentation for the JSON-schema-based system for on-the-fly parameter pop-up. Which is used by the GPhL workflow integration, but is completely general. It is in active use with mxcubeqt (mxcubeqt/utils/paramsgui.py) , but Jean-Baptiste is just now beginning to look at implementing it for mxcubeweb as well.

I am not really sure where all this should go (help, anyone?). There is about 20 example JSON files (in that directory), and a documentation page with half a dozen screenshots plus text that  I put on the mxcubecore WIki (https://github.com/mxcube/mxcubecore/wiki/JSON-schema-generated-user-interface) for want  of a better place to put it.

I'd be very happy to move it if anyone could tell me what was the logical place for it.

**Comment by fabcor-maxiv** [comment]
@rhfogh Thanks for the details. For now I will setup some kind of blank skeleton for the Sphinx-based documentation. Then we can discuss what should be where, whether it makes sense to migrate those JSON examples, and so on.

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson This will require you to re-do the same procedure at readthedocs.org as you did for *mxcubeweb*.

**Comment by marcus-oscarsson** [comment]
Thanks @fabcor-maxiv ill take care of it :)

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson I see the `readthedocs.yaml` files has been added. Thanks! Can you add me as maintainer to the project in *Read the docs*?

**Comment by marcus-oscarsson** [comment]
Oh yes, forgot that bit :)
