### ISSUE TITLE
Move wiki content to `/docs`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#831]
Now that we have the setup with Sphinx (and ReadTheDocs) automatically building documentation, and now that we have the "documentation camp" in perspective, I want to start working a bit more on content. First things first, I want to move the content of the wiki to the new Sphinx-based setup in `/docs`.

So this is a follow-up to https://github.com/mxcube/mxcubecore/issues/797 and https://github.com/mxcube/mxcubecore/issues/804, and it is related to https://github.com/mxcube/mxcubecore/issues/812.

**Comment by fabcor-maxiv** [comment]
@rhfogh wrote in https://github.com/mxcube/mxcubecore/issues/797#issuecomment-1739412887 :

>  a documentation page with half a dozen screenshots plus text that I put on the mxcubecore WIki (https://github.com/mxcube/mxcubecore/wiki/JSON-schema-generated-user-interface) for want of a better place to put it.
> 
> I'd be very happy to move it if anyone could tell me what was the logical place for it.

Should we proceed with this? It seems to be the only wiki page currently. I can do the copy-paste into `/docs`.

**Comment by marcus-oscarsson** [comment]
Indeed, I think that section can be moved to docs without any problem
