### ISSUE TITLE
Do we need a range for the Python version in `conda-environment-dev.yml`?

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#845]
I [wrote](https://github.com/mxcube/mxcubecore/issues/836#issue-2081659864):

> I am not sure we need to have a version range for Python in the `conda-environment-dev.yml` file. Maybe it is better to choose a version (major minor, for example `3.10`), and then use the same for pre-commit hooks and everywhere else it makes sense.

@rhfogh [wrote](https://github.com/mxcube/mxcubecore/issues/836#issuecomment-1892061723):
> Before we change the python version specified, we need to make sure that all installations are OK with that version. Essentially whatever version is specified in conda-environment-dev.yml would count as a de facto minimum version for installations, no?

@marcus-oscarsson [wrote](https://github.com/mxcube/mxcubecore/issues/836#issuecomment-1892360455):

> The reason for the version range is that not all institutes support/use the same version for python on their beamlines.

---

My intention is not to change the Python version range in Poetry `pyproject.toml` which is the one that declares what Python versions are supported by this library.

The way I see it, `conda-environment-dev.yml` is only to set up a development environment quickly. Is there a way with the current version of this file to choose something else than Python 3.10 when creating the conda environment?

**Comment by marcus-oscarsson** [comment]
You are right that one would like to use this for whatever python version one intends to use, so the range is maybe not really necessary. One needs to either pass python version via command line or edit the file to get the wanted result.

**Comment by fabcor-maxiv** [comment]
Seems like something like this works:

```bash
conda create --file conda-environment-dev.yml python=3.9
```

and this fails (as we would want):

```bash
conda create --file conda-environment-dev.yml python=3.7
```

**Comment by marcus-oscarsson** [comment]
Yeah, thats what I had in mind, but not sure that passing python version will override whats i the  `yaml`, did you try ?

**Comment by fabcor-maxiv** [comment]
Yes, that is what I meant. I tried both the commands in my previous message.

We could document this somewhere, although I assume it is kind of basic conda knowledge. On mxcubecore we do not really have a good place to document this, but we could do it for mxcubeweb at least.

**Comment by marcus-oscarsson** [comment]
:+1:  ok sounds good. It is basic conda knowledge and its, I would say, the expected behavior

**Comment by fabcor-maxiv** [comment]
Let's close this. See the following instead:

* https://github.com/mxcube/mxcubecore/issues/848
* https://github.com/mxcube/mxcubeweb/pull/1163

**Comment by marcus-oscarsson** [comment]
:+1: Thanks !
