### ISSUE TITLE
May code camp topics

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#863]
During our last meeting we decided to do a sort of poll for the topic(s) of the Maye code camp (the one that will take place in association with the MXCuBE meeting). 

_The preliminary dates are 28th to 30th of May, with the ISPyB meeting taking place the 28th. **Please note that the dates are preliminary and needs to be confirmed.**_

Below are some suggestions from recent discussion topics,  please feel free to make your suggestions !

- Continue documentation
- YAML configuration
- Centring
- Queue architecture
- Unattended data collection

**Comment by rhfogh** [comment]
The best time to do a code camp is when you want to do some serious work on an issue - to get it started. I'd say that the best candidate for this (if we feel we are ready) is YAML configuration. The others are either already started (documentation) or maybe not yet ready for a concerted push.

**Comment by fabcor-maxiv** [comment]
Working on (YAML) configuration seems a good idea.

On the other hand, I wonder if this topic is accessible enough for everyone to participate in. It all depends how we organize this, of course. But my first reaction, is that I am not sure I would be able to do much on this topic. I also worry about the efficiency of the camp if there are too many newbies (on this topic, like me) for whom the topic has to be "dumbed down".

Maybe, if this is the topic that gets chosen, then there could be another topic running parallel to this, which is easier of access. Maybe it is unnecessary worry from my side.

**Comment by rhfogh** [comment]
Dear Fabien,

You are right it could be tough - I would surely need to prepare some 
code we could work with in preparation (Oh Dear! the time!).

Could a few people react to mxcubecore Issue #897 
(https://github.com/mxcube/mxcubecore/issues/897) where I have set out a 
game plan? If there is some kind of feed-back (or preferably consensus) 
on the way forward it would be a lot easier to prepare something.

Yours,
Rasmus

**Comment by marcus-oscarsson** [comment]
I think its a good idea to possibly have two or perhaps even more topics to choose from. More than two might become to much to manage but it also depends on what they are. In my opinion the XML to YAML topic is both important and complex enough that it benefits from some sitting down together and discussing. 

We can have a separate track with for instance documentation for those who think that is more interesting or where they are most efficient.

**Comment by marcus-oscarsson** [comment]
I think its a good idea to possibly have two or perhaps even more topics to choose from. More than two might become to much to manage but it also depends on what they are. In my opinion the XML to YAML topic is both important and complex enough that it benefits from some sitting down together and discussing. 

We can have a separate track with for instance documentation for those who think that is more interesting or where they are most efficient.
