### ISSUE TITLE
What about a "last updated on" timestamp on documentation pages?

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#899]
Maybe it would be useful to have a "last updated on" timestamp on documentation pages.

Maybe this could help: https://pypi.org/project/sphinx-last-updated-by-git/

**Comment by fabcor-maxiv** [comment]
This is low priority, but nice to have I guess.

**Comment by fabcor-maxiv** [comment]
Other potential solution: <https://pypi.org/project/sphinx-gitstamp/>

**Comment by marcus-oscarsson** [comment]
Why not, I guess it can reduce the uncertainty ?

**Comment by marcus-oscarsson** [comment]
Are you still considering doing this :), otherwise we can perhaps close it for now ?

**Comment by fabcor-maxiv** [comment]
Yes :)

* Pull request:
  *  https://github.com/mxcube/mxcubecore/pull/939

* Preview (there should be a timestamp at the bottom of each page):

  * https://mxcubecore--939.org.readthedocs.build/en/939/
