### ISSUE TITLE
Deployment to GitHub Pages is not enabled

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcubecore#904]
We have a GitHub Actions workflow that builds the documentation (the Sphinx thing), and attempts to deploy it to GitHub pages <https://mxcube.github.io/mxcubecore>. So it should be an exact mirror of <https://mxcubecore.readthedocs.io/en/stable/>. It does not cost much to have this, it is all automated and should be low maintenance.

But according to runs such as [this one](https://github.com/mxcube/mxcubecore/actions/runs/8373758621), deployment to GitHub Pages is not enabled:

> Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action.

**Comment by fabcor-maxiv** [comment]
Maybe @marcus-oscarsson can help with that.

**Comment by marcus-oscarsson** [comment]
Id be happy to, but you should also be able to do it, I think you have the rights ?

**Comment by marcus-oscarsson** [comment]
But wait, what is that we are deploying on the GitHub pages ?

**Comment by fabcor-maxiv** [comment]
> But wait, what is that we are deploying on the GitHub pages ?

Currently, nothing as far as I can tell (since it is not enabled). And the idea would be to have the same content that is on Readthedocs. So, not necessary, but since it is all automated and already taken care of, I thought why not...

**Comment by marcus-oscarsson** [comment]
Ok, hm. I don't mind enabling it or if you want to do it, as I said you should have the rights. But does it not seem unnecessary to have documentation in two places, I know its for free and all but still ?

**Comment by marcus-oscarsson** [comment]
I enabled the basic pages option but it maybe needs some more configuration, I let you have a look in that case

**Comment by fabcor-maxiv** [comment]
> I don't mind enabling it or if you want to do it _[...]_. But does it not seem unnecessary to have documentation in two places, I know its for free and all but still ?

I would like to try it at least, yes. I would like to see how it behaves. If it is an annoyance rather than anything else, it is easy to get rid of it.


> you should have the rights

My account does not allow me to see the repository settings, no.


> I enabled the basic pages option but it maybe needs some more configuration, I let you have a look in that case

Thanks. It should deploy with the next merged pull request. We'll see...

**Comment by marcus-oscarsson** [comment]
Hm thats odd I thought I added you as administrator, ill have another look

**Comment by marcus-oscarsson** [comment]
Ok, I tried to add you again you should have an invite and I hope you are able to se the repository settings ?

**Comment by marcus-oscarsson** [comment]
Closing this one, let me know if it works as you expect

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson It has indeed deployed: https://mxcube.github.io/mxcubecore/

**Comment by fabcor-maxiv** [comment]
Today it pays off...

The following URL:
https://mxcubeweb.readthedocs.io/en/latest/dev/autosummary/mxcubeweb.config.html
currently shows this:
![image](https://github.com/mxcube/mxcubecore/assets/140523662/a7a24276-6710-48b4-9bba-21d52d5a082e)

So we have this mirror:
https://mxcube.github.io/mxcubeweb/dev/autosummary/mxcubeweb.config.html
