### ISSUE TITLE
UML diagrams in documentation

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcubecore#951]
Adding the possibility to add UML diagrams via for instance [plantuml](https://github.com/sphinx-contrib/plantuml), what do you think is it practical or is there a better way of doing it ?

**Comment by fabcor-maxiv** [comment]
Yes, we had discussed this already here: https://github.com/mxcube/mxcubecore/pull/889#discussion_r1534128479

I can have a closer look at this in the next days and come up with a concrete proposal (a pull request).

**Comment by fabcor-maxiv** [comment]
Let's close this in favor of this other older ticket: https://github.com/mxcube/mxcubecore/issues/908
