### ISSUE TITLE
Moving XML nested properties to YAML

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#977]
@elmjag noted that the xml_yaml_conversion branch did not work for nested properties, which were simply not found in get_properties.
Looking closer there is a clear bug. The properties for xml-configured objects in the new shared XML/YAML code are set by getting the properties from HardwareObjectNode.get_properties(). The problem is that nested XML elements, more precisely XML elements that contain other elements are not treated as properties, but as contained objects, and so are not in get_properties. 

Looking through the startup (Qt version, mock mode) there are two different type of case:

These are:

1) Properties that are simple dictionaries. 

- Session.file_info
- Slits.gapH
- Slits.gapV
- Detector.beam 
- SampleChangerMockup.test_sample_names
- Gphl-CollectEmulator.simcal_parameters
- Gphl-CollectEmulator.simcal_options
- Gphl-CollectEmulator.environment_variables

These can be handled very simply by converting teh data to a single property that is a dictionary, and I am starting to code this.

2) Properties that are lists of dictionaries. These are:

- EnergyScan.mad
- EnergyScan.elements
- OfflineProcessing.programs

The structure of these can be seen in this example:
```

<programs>
    <program>
        <executable>path_to_edna_autoproc.sh</executable>
        <event>after</event>
    </program>
    <program>
        <executable>path_to_edna_thumb.sh</executable>
        <event>image</event>
    </program>
</programs>

```

Writing temporary code that read this kind of data structure would be a lot more messy, particularly if you wanted it to be able to deal with arbitrary  nested data structures (that are likely not present in the current MXCuBE). 

I would propose that we do *not* fix the problem in handling this kind of nested data structure, but simply make the necessary changes to the code as we upgrade the relevant config files. Arguments in favour would be 1) that this is a very limited part of the code and so should be tractable. 2) that there is really no obvious mapping, since a dictionary containing a single list of dictionaries is not the kind of data structure you would really want. 

What do people think of this?

**Comment by marcus-oscarsson** [comment]
There is this `xmltodict` project: https://pypi.org/project/xmltodict/, Ive used it abit in the past and it seems to work quite well. Perhaps it can be of help ?

**Comment by rhfogh** [comment]
On second thoughts I shall make a PR where the programs example above is translated into property as

obj.programs = [
  { 
    "executable": "path_to_edna_autoproc.sh",
    "event": "after",
  },
  { 
    "executable": "path_to_edna_thumb.sh",
    "event": "image",
  },
]

This would likely still require a code change, but at least there would be something to work with.

**Comment by elmjag** [comment]
> On second thoughts I shall make a PR where the programs example above is translated into property as
> 
> obj.programs = [ { "executable": "path_to_edna_autoproc.sh", "event": "after", }, { "executable": "path_to_edna_thumb.sh", "event": "image", }, ]
> 
> This would likely still require a code change, but at least there would be something to work with.

I think it sound reasonable that we get a list of dictionary in this case.

Regarding code changes. As far as I understand we agreed that code changes to HWOBJs are acceptable. 

However, we are aiming to be able to support XML and YAML configs at the same time, with the same implementation of the HWOBJ, to make it easier for gradual migration to YAML.

**Comment by rhfogh** [comment]
Coming back, I think there must be a mistake here.

Running the xml_yaml_conversion branch I find 

1) that the output session.yml, energy_scan.yml, beam.slits.yml, detector.yml, and offline_processing.yml DO contain the nested properties that according to the xml files they should. 

2) If I put print statements in mxcubecore.HardwareRepository in lines 383-384, at the end of the init_hardware_repository function as follows:
    print ('@~@~ Session', beamline.session.get_properties())
    print ('@~@~ EnergyScan', beamline.energy_scan.get_properties())
I DO get the nested repositories returned from get_properties(). And this si WITYHOUT having made any paerticular changes.

Elmir, could you double check if you get the same results? Could it be that you are missing the nested attributes because you are putting your tests too early, before the loading process is finished? The nested attiributes are  not set till in _attach_xml_objects, called from  line 207 of HArdwareRepository.load_from_yaml

**Comment by elmjag** [comment]
> Coming back, I think there must be a mistake here.
> 
> Running the xml_yaml_conversion branch I find
> 
> 1. that the output session.yml, energy_scan.yml, beam.slits.yml, detector.yml, and offline_processing.yml DO contain the nested properties that according to the xml files they should.
> 2. If I put print statements in mxcubecore.HardwareRepository in lines 383-384, at the end of the init_hardware_repository function as follows:
>    print ('@~@~ Session', beamline.session.get_properties())
>    print ('@~@~ EnergyScan', beamline.energy_scan.get_properties())
>    I DO get the nested repositories returned from get_properties(). And this si WITYHOUT having made any paerticular changes.
> 
> Elmir, could you double check if you get the same results? Could it be that you are missing the nested attributes because you are putting your tests too early, before the loading process is finished? The nested attiributes are not set till in _attach_xml_objects, called from line 207 of HArdwareRepository.load_from_yaml

Yes, both 1 and 2 work fine for me. However, I'm trying to access properties in Session.init() method. Try adding, `self.get_properties()` call at line 56 in `mxcubecore/Session.py` file. For example, apply this patch:

```
diff --git a/mxcubecore/HardwareObjects/Session.py b/mxcubecore/HardwareObjects/Session.py
index dd80bc2d6..ca754fd5f 100644
--- a/mxcubecore/HardwareObjects/Session.py
+++ b/mxcubecore/HardwareObjects/Session.py
@@ -53,6 +53,7 @@ class Session(HardwareObject):
         self.beamline_name = self.get_property("beamline_name")
         self.endstation_name = self.get_property("endstation_name").lower()
 
+        print(f"Session properties:\n", self.get_properties())
         self.suffix = self["file_info"].get_property("file_suffix")
         self.template = self["file_info"].get_property("file_template")

```

If you run the patch above with XML config file, you'll get following output:

```
Session properties:
 {'synchrotron_name': 'ESRF', 'endstation_name': 'mxcubewebtest', 'beamline_name': 'mxcubewebtest', 'email_extension': 'esrf.fr', 'feedback_email': 'test@...'}
```

For example the `file_info` key is missing above. If you run the same code using YAML, you'll get all properties, as expected. Not having all properties available in `init()` method is of course problematic.

For the reference, here is the version of `Session.init()` I want to make work with both XML and YAML configs.

https://github.com/elmjag/mxcubecore/blob/e958a9a5ffe089d32f95bba2ca90060141df9ec9/mxcubecore/HardwareObjects/Session.py#L51

**Comment by rhfogh** [comment]
Here I must ask: Why would you want to copy the configured properties from _config to top level attributes?

In my very first proposal, configured properties were directly and automatically put into the top level, and you would expect to access them there  - no extra code would have been necessary. But it was agreed that the configured properties should instead be put in _config (which would be a Pydantic object). In this configuration, the correct way to access e.g. beamline_name is 
`self.config.beamline_name`
and the correct way to access file_template is 
`self.config.file_info.get("file_template")`

And, if I am not mistaken, that should work for both YAML and XML-configured objects already - provided that you wait till the loading is finished. It seems that you are only getting the problem because you want to rearrange the structure of the configuration parameters while the loading is still going on.

Surely we should make a system for configuration parameters, and then use that system? Not sometimes copy them to a different location, so that you are never sure where you should look for a configured parameter in any particular case. Would it not be a lot simpler simply to access configuration parameters through obj.config everywhere in the code, and so avoid this problem altogether?

Is there is a use case for accessing these config parameters from the init that can not be avoided in this way, and that cannot be fudged until we have finished the transition? If so, what would it be?

**Comment by elmjag** [comment]
Aha, I did not understand that you are supposed to use `config` attribute. I was under impression that `_config` was internal implementation attribute, not to be accessed directly.

Perhaps we should even mark `get_properties()` and `get_property()` as deprecated? We should aim for have only _one_ way to access HWOBJ configuration, right?

> Here I must ask: Why would you want to copy the configured properties from _config to top level attributes?
> 
> In my very first proposal, configured properties were directly and automatically put into the top level, and you would expect to access them there - no extra code would have been necessary. But it was agreed that the configured properties should instead be put in _config (which would be a Pydantic object). In this configuration, the correct way to access e.g. beamline_name is `self.config.beamline_name` and the correct way to access file_template is `self.config.file_info.get("file_template")`
> 
> And, if I am not mistaken, that should work for both YAML and XML-configured objects already - provided that you wait till the loading is finished. It seems that you are only getting the problem because you want to rearrange the structure of the configuration parameters while the loading is still going on.
> 
> Surely we should make a system for configuration parameters, and then use that system? Not sometimes copy them to a different location, so that you are never sure where you should look for a configured parameter in any particular case. Would it not be a lot simpler simply to access configuration parameters through obj.config everywhere in the code, and so avoid this problem altogether?
> 

Yes, I agree. These is no reason to copy config properties to object attributes. This is how the current implementation of Session looks like right now.

I'll try to refactor it, so it does not copy config properties.

> Is there is a use case for accessing these config parameters from the init that can not be avoided in this way, and that cannot be fudged until we have finished the transition? If so, what would it be?

Not sure. Theoretically speaking it's possible there are reasonable use cases. But yeah, maybe they don't exist in reality.

Let's ignore this issue for now. I'll work on refactoring Session object and we'll see if it's possible to avoid this issue.

**Comment by rhfogh** [comment]
@elmjag Yeah, I had kind of forgotten myself, until I refreshed my memory.

`_config` is internal, but there is a property `.config` that returns it.

Deprecating get_property and get_properties might be nice, but it depends a bit. For get_property there is the niggle that you can call it with a default value, so that if there is no such property you will get the default value instead. There might be a use case for that. `get_properties` is basically an alias for `self._config.model_dump()`. 

What do other people think?

**Comment by elmjag** [comment]
> > Is there is a use case for accessing these config parameters from the init that can not be avoided in this way, and that cannot be fudged until we have finished the transition? If so, what would it be?
> 
> Not sure. Theoretically speaking it's possible there are reasonable use cases. But yeah, maybe they don't exist in reality.
> 
> Let's ignore this issue for now. I'll work on refactoring Session object and we'll see if it's possible to avoid this issue.

I started refactoring Session object, but realized that `self.config` was not available when XML configure file is used. I could not come up with a way around that.

I made this patch instead:  https://github.com/mxcube/mxcubecore/pull/980/files

This makes `self.config` available, with all data, both when using XML and YAML.

Not sure if this change breaks anything, but it solves my issues with Session HWOBJ. The current mocked beamline (test/HardwareObjectsMockup.xml), loads and runs fine in MXCuBE-web, as far as I can tell.

I have now a version of Session HWOBJ that works both with XML and YAML configuration files:
https://github.com/elmjag/mxcubecore/blob/1a58568dd8244db208deb7aa4f6146c35ab128b6/mxcubecore/HardwareObjects/Session.py

**Comment by rhfogh** [comment]
@elmjag Yeah, that ought to work - and it means that we no longer have an obligation of avoiding property access from the init functions, which is good. Thanks.

Session is not completely clean now (with properties that just return the config value, ugh!), but with a mixture of attributes that are configured directly and attributes that are calculated at initialisation time, and all those functions that get and set directories it would take a *lot* of refactoring to make it clean - and for little gain.

**Comment by elmjag** [comment]
Fixed on `xml_yaml_conversion` branch.
